packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - argon2
  - esbuild
  - prisma
allowBuilds:
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  argon2: set this to true or false
  esbuild: set this to true or false
  prisma: set this to true or false
